### ISSUE TITLE
Magnetized compass resets lodestone position after opening inventory

### ISSUE THREAD

**Issue by Zemenus** [joshuaprince/CoordinateOffset#10]
I clicked on the lodestone with compass, everything was fine until I looked into my inventory. Compass got updated right in my hands and it points into another direction.

Environment details

Output of /version:
Current: git-Purpur-2127 (MC: 1.20.4)*
Previous: git-Purpur-2084 (MC: 1.20.2)
* You are running the latest version

CoordinateOffset version: v3.0.0
PacketEvents/ProtocolLib version: 5.2.0 SNAPSHOT 679
Output of /plugins: there are only Ofssets dependency plugins and, well, CoordinateOffset

Log errors
Console didn't write any errors when that occured

Additional context
It does that with new compasses too. I also checked NBT data of compass. When I click onto the lodestone and DO NOT open my inventory, coordinate is right in NBT tag, and then, I open my inventory, it updates the compass, and the lodestone position in its NBT tag changes into different position (probably position of the offset?)

**Comment by joshuaprince** [comment]
Are you in Creative mode when you try this? I've run into similar issues while testing in Creative, but it does not happen in Survival/Adventure since clients cannot affect the NBT of items in their inventory outside of Creative.

**Comment by Zemenus** [comment]
Yeah, you are right, in survival it won't update itself

**Comment by joshuaprince** [comment]
Fixed in Creative in [v3.0.2](https://github.com/joshuaprince/CoordinateOffset/releases/tag/v3.0.2)
