### ISSUE TITLE
Support 1.17 and 1.18?

### ISSUE THREAD

**Issue by RE4ERKA** [joshuaprince/CoordinateOffset#3]
Add support for versions 1.17 and 1.18 to support the plugin on more servers.

**Comment by joshuaprince** [comment]
I will consider older version support if there is demand for it, but there are at least a few challenges in backporting:

- Modifying the packet translation logic to support previous versions of the Minecraft protocol
- Removing uses of new API features throughout plugin logic
- Ensuring ongoing support for all versions (i.e. lots of extra testing on plugin and game updates)

If anyone is interested in contributing, I would be happy to consider pull requests that accomplish these. For now, while the plugin is still relatively new, I'd prefer to take Paper's approach of only supporting the latest few game versions.

**Comment by joshuaprince** [comment]
Server versions down to 1.17.1 are supported as of [v2.3.0](https://github.com/joshuaprince/CoordinateOffset/releases/tag/v2.3.0).
