### ISSUE TITLE
[BUG] Exception Connecting: QuietException

### ISSUE THREAD

**Issue by Yavoroshko** [joshuaprince/CoordinateOffset#5]
Using:
ProtocolLib 5.1.0, also tried Jenkins last builds
Paper 1.20.1 #194
CoordinateOffset v2.1.2
FlameCord 1.6.4

When trying to connect to server I have an error in chat

Exception Connecting: QuietException : Unexpected packet received during server connector process!
0a004940e86a0000000000
Nothing more in console of proxy and console of Hub server and server where the plugin installed

Also I don't get this error when using CoordinatesObfuscator 1.4.14 but I can't use it because I can`t normally use worldborder

Also tried on local because maybe it is because of fork of proxy
Using:
ProtocolLib 5.1.0
Paper 1.20.1 #194
CoordinateOffset v2.1.2
waterfall 1.20 536

And 2 servers:
Hub without CoordinateOffset but with ProtocolLib 5.1.0
Survival with CoordinateOffset and ProtocolLib 5.1.0
No other plugins installed

net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
49418c9c3800000000 in Proxy console and chat

**Comment by Yavoroshko** [comment]
Tried to add CoordinateOffset to Hub server too, didn't work.

Tried without proxy and plugin works. But still need fix for proxy.

**Comment by joshuaprince** [comment]
Thank you for the report! Please try out [v2.1.3](https://github.com/joshuaprince/CoordinateOffset/releases/tag/v2.1.3) and see if it fixes the issue.

**Comment by Yavoroshko** [comment]
It looks like it works, thanks!
